version: '3.3'
services:
    backend:
        build: ./backend
        expose:
            - '8000'
        command: >      
            bash -c "python manage.py migrate --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - .:/bank

    nginx:
        restart: always
        build: ./nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - .:/bank
        depends_on:
            - backend
