# Generated by Django 4.2.5 on 2023-09-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_a_user_groups_a_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='a_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
