# Generated by Django 4.2.5 on 2023-10-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expired',
            field=models.DateField(auto_now=True),
        ),
    ]
