# Generated by Django 4.2.5 on 2023-10-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_favourites_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='goods',
            field=models.ManyToManyField(blank=True, to='shop.good'),
        ),
        migrations.AlterField(
            model_name='good',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='shop.review'),
        ),
    ]
