# Generated by Django 4.2.5 on 2023-11-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_ordergoods_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='bought',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
